### ISSUE TITLE
python 2 in 2021, are you serios?

### ISSUE THREAD

**Issue by antonkulaga** [senaite/senaite.lims#130]

**Comment by ramonski** [comment]
Hi @antonkulaga,
instead of posting empty issues in sense and content like this, you are welcome to contribute with a code PR to make it happen:

- https://github.com/senaite/senaite.core/blob/2.x/P8_UPGRADE_GUIDE.md
- https://github.com/senaite/senaite.core/blob/2.x/CONTRIBUTING.md

Thanks, and I'm closing this one for now...
