### ISSUE TITLE
Accreditation logo and schedule not displayed

### ISSUE THREAD

**Issue by lemoene** [senaite/senaite.lims#35]
## Steps to reproduce

navigate anoymously to LIMS front page (a client prospect)

## Current behavior

![image](https://user-images.githubusercontent.com/1196034/34320363-58ca8b92-e801-11e7-9cf2-994d48e0a70a.png)

note that /accreditation does exist 

## Expected behavior
Accredited lab's 'Seal' displayed and clickable for Accreditation schedule

![image](https://user-images.githubusercontent.com/1196034/34320376-b55e7e2c-e801-11e7-8c37-779603abd23a.png)

## Screenshot (optional)

is set up, bika_setup/laboratory

![image](https://user-images.githubusercontent.com/1196034/34320389-01340c18-e802-11e7-8d76-d3f686175adb.png)

**Comment by ramonski** [comment]
This portlet was removed per default, because it would need to have the whole `bika_setup` object accessible by unauthenticated users. We changed the default permissions, so that this is not possible anymore, which caused a portlet error on the front-page if you are not logged in.

However, you can easily re-apply this portlet by adding a classic portlet with the macro `portlet_accreditation`:

<img width="563" alt="__ _senaite" src="https://user-images.githubusercontent.com/713193/34320700-38a417c6-e800-11e7-8711-2c26ea342fdb.png">

But the lab could also easily add a "static text portlet" and upload that image in there, without any side-effects.

**Comment by lemoene** [comment]
cool, thanks. Am I logging in the right tracker. Have a UI recommendation or 2. I'll continue here for now, move them as applicable
